
seed: 42

wandb:
    save_dir: './logging'
    checkpoint_directory: './models_checkpoint'
    offline: False
    project: 'Segmentation-Texts'
    progress_bar_refresh_rate: 10

sbert:
    st_checkpoint: 'paraphrase-multilingual-MiniLM-L12-v2'
    batch_size: 64
    bert_checkpoint: 'bert-base-uncased'
    emb_type: 'SBERT'
    freeze_bert: True
    learning_rate: 0.00001
    class_weight: null

labse:
    lb_checkpoint: 'cointegrated/LaBSE-en-ru'
    batch_size: 64
    bert_checkpoint: 'bert-base-uncased'
    emb_type: 'LABSE'
    freeze_bert: True
    learning_rate: 0.00001
    class_weight: null

bilstm:
    vocab_size: 768
    embedding_dim: 512
    hidden_dim1: 256
    hidden_dim2: 128
    n_layers: 4
    bidirectional: True
    lr: 0.000003
    class_weight: null